version: '3.8'

networks:
  wise_network:
    driver: bridge

services:
  postgres_client:
    image: postgres:15
    container_name: wise-postgres_client
    environment:
      POSTGRES_DB: clientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - wise_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clientdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_order:
    image: postgres:15
    container_name: wise-postgres_order
    environment:
      POSTGRES_DB: wise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - wise_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wise"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_product:
    image: postgres:15
    container_name: wise-postgres_product
    environment:
      POSTGRES_DB: wiseCommerceProduct
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - wise_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wiseCommerceProduct"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_stock:
    image: postgres:15
    container_name: wise-postgres_stock
    environment:
      POSTGRES_DB: stock_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    networks:
      - wise_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stock_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_payment:
    image: postgres:15
    container_name: wise-postgres_payment
    environment:
      POSTGRES_DB: wisePayment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    networks:
      - wise_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d wisePayment" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: wise-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: wise
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wise_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  wise-client-service:
    build:
      context: ./wise-client-service
      dockerfile: ./Dockerfile
    container_name: wise-client-service
    depends_on:
      postgres_client:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - wise_network
    restart: unless-stopped

  wise-order-service:
    build:
      context: ./wise-order-service
      dockerfile: ./Dockerfile
    container_name: wise-order-service
    depends_on:
      postgres_order:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8080"
    networks:
      - wise_network
    restart: unless-stopped

  wise-product-service:
    build:
      context: ./wise-product-service
      dockerfile: ./Dockerfile
    container_name: wise-product-service
    depends_on:
      postgres_product:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8089:8080"
    networks:
      - wise_network
    restart: unless-stopped

  wise-order-receiver:
    build:
      context: ./wise-order-receiver
      dockerfile: ./Dockerfile
    container_name: wise-order-receiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8084:8080"
    networks:
      - wise_network
    restart: unless-stopped

  wise-payment:
    build:
      context: ./wise-payment
      dockerfile: ./Dockerfile
    container_name: wise-payment
    depends_on:
      postgres_payment:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8085:8080"
    networks:
      - wise_network
    restart: unless-stopped

  wise-stock-service:
    build:
      context: ./wise-stock-service
      dockerfile: Dockerfile
    container_name: wise-stock-service
    depends_on:
      postgres_stock:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8088:8080"
    networks:
      - wise_network
    restart: unless-stopped